---
# tasks file for docker-install

# Setup/install tasks.
- include_tasks: install-CentOS.yml
  when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- include_tasks: install-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


