---
- hosts: aws
  vars:
    - delete_docker: false
    - delete_docker_data: false
    - perform_reboot: true
    - run_jenkins: true
  roles:
#    - docker-remove
    - docker-install
#    - reboot_and_start_jenkins

