---
- hosts: aws
  vars:
    - delete_docker: true
    - delete_docker_data: true
    - perform_reboot: true
    - run_jenkins: true
  roles:
    - docker-remove
    - docker-install
#    - reboot_and_start_jenkins

