---
- name: apt-get update
  apt:
    update_cache: yes

- name: Install
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl 
      - gnupg 
      - lsb-release

- name: Install key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Install repo
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: apt-get update
  apt:
    update_cache: yes

- name: Install Docker packages {{ packages }}
  apt:
    name: "{{ packages }}"
    force: yes
    state: latest
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

