---
- name: Adding docker repo
  include_role:
    name: docker-add-repo

- name: Uninstall Docker packages {{ packages }} 
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker 
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

