---
- name: Adding docker repo
  include_role:
    name: docker-add-repo

- name: Uninstall Docker packages {{ packages_delete }} 
  yum:
    name: "{{ packages_delete }}"
    state: absent
  vars:
    packages_delete:
    - docker 
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

- name: Installing Docker Ce
  yum:
    name: "{{ packages_install }}"
    state: present
  vars:
    packages_install:
      - docker-ce
      - docker-ce-cli
      - containerd.io
