---
- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: 
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Uninstall Docker packages {{ packages }} 
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - docker 
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Delete ALL docker data Delete data = {{ delete_docker_data }}  
  file:
    state: absent
    path: /var/lib/docker/
  when: delete_docker_data|bool == true 
